
#Item Scrapper Rendering Configuration
[rendering]
	#Maximum number of items to render for the input item (visual only)
	#This does not affect the actual capacity of the input slot, only how many items are shown
	#Range: 1 ~ 64
	maxInputItemsRendered = 64
	#Maximum number of items to render for each output slot (visual only)
	#This does not affect the actual output capacity, only how many items are shown
	#Range: 1 ~ 64
	maxOutputItemsRendered = 64

