StakeWallDamageMultiplier = 1.0
StakeDamageMultiplier = 1.0
SpikeDamageMultiplier = 1.0
BarbedWireDamageMultiplier = 1.0
BarbedIvyWireDamageMultiplier = 1.0
#This variable represents time in ticks. 20 ticks = 1 second
GrassTrapTime = 5.0

