#The Y value in which void fog takes effect. (Min World Height + Y Value)
#Range: > 0
y = 12
#Defines how far away the fog should be from your player. Higher numbers mean further away.
#Range: 0.0 ~ 1.7976931348623157E308
distance = 30.0
#Enable the effect everywhere in the mod Voidscape's main Dimension.
voidscape = true
#Defines which dimensions shouldnt render any void fog. Each entry should be a valid dimension id. For example, to blacklist void fog from appearing in Twilight Forest, add "twilightforest:twilight_forest" to this list.
dimension_blacklist = []
#Defines whether the dimension blacklist should function as a whitelist instead, meaning that only dimensions in that config option will render void fog.
toggle_whitelist = false

